### ISSUE TITLE
Error with Red 3.1.1

### ISSUE THREAD

**Issue by Lewimaron** [skeith/MayuYukirin#4]
After updating red to 3.1.1 I get the following error when running the avatar command;

```Exception in command 'avatar'
Traceback (most recent call last):
  File "/home/lewimaron/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/lewimaron/reddata/cogs/CogManager/cogs/avatar/avatar.py", line 39, in avatar
    u = await ctx.bot.get_user_info(user.id)
AttributeError: 'Red' object has no attribute 'get_user_info'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lewimaron/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "/home/lewimaron/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/lewimaron/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Red' object has no attribute 'get_user_info'```
